# Development environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_dev
    user: "${UID:-1000}:${GID:-1000}"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./api:/app
      - ./api/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./api/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  pwa:
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/srv/app
    environment:
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: http://php
      API_PLATFORM_CREATE_CLIENT_OUTPUT: .
      # On Linux, you may want to comment the following line for improved performance
      WATCHPACK_POLLING: "true"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
