App\Entity\Instructor:
    attributes:
        firstName:
            groups: [ 'instructor:list', 'instructor:read', 'instructor:write', 'course:read', 'course:list' ]
        lastName:
            groups: [ 'instructor:list', 'instructor:read', 'instructor:write', 'course:read', 'course:list' ]
        specialty:
            groups: [ 'instructor:list', 'instructor:read', 'instructor:write', 'course:read', 'course:list' ]
