App\Entity\Course:
    properties:
        title:
            - NotBlank: ~
            - Length: { min: 3, max: 255 }
        description:
            - NotBlank: ~
        level:
            - Choice:
                callback: [App\Entity\Enum\Level, cases]
        priceInCents:
            - PositiveOrZero: ~
        maxStudents:
            - Positive: ~
        status:
            - Choice:
                callback: [App\Entity\Enum\Status, cases]
        instructor:
            - NotNull: ~
