App\Entity\Module:
    properties:
        title:
            - NotBlank: ~
        content:
            - NotBlank: ~
        position:
            - PositiveOrZero: ~
        durationInMinutes:
            - PositiveOrZero: ~
