resources:
    App\Entity\Course:
         normalizationContext:
             groups: ['course:read']
         denormalizationContext:
             groups: ['course:write']
         operations:
             ApiPlatform\Metadata\GetCollection:
                 normalizationContext:
                     groups: ['course:list']
                 cacheHeaders:
                     shared_max_age: 3600
                     max_age: 60
                     stale_while_revalidate: 60
             ApiPlatform\Metadata\Get:
                 provider: App\State\CachedItemProvider
                 cacheHeaders:
                     shared_max_age: 3600
                     max_age: 60
                     stale_while_revalidate: 60
             ApiPlatform\Metadata\Post:
                 processor: App\State\IdempotentProcessor
             ApiPlatform\Metadata\Patch: ~
             ApiPlatform\Metadata\Delete: ~
properties:
    App\Entity\Course:
        id:
            identifier: false
        uuid:
            identifier: true
