resources:
    App\Entity\Instructor:
         normalizationContext:
             groups: ['instructor:read']
         denormalizationContext:
             groups: ['instructor:write']
         operations:
             ApiPlatform\Metadata\GetCollection:
                 cacheHeaders:
                     shared_max_age: 3600
                     max_age: 120
             ApiPlatform\Metadata\Get:
                 cacheHeaders:
                     shared_max_age: 3600
                     max_age: 120
             ApiPlatform\Metadata\Post: ~
             ApiPlatform\Metadata\Patch: ~
             ApiPlatform\Metadata\Delete: ~
properties:
    App\Entity\Instructor:
        id:
            identifier: false
        uuid:
            identifier: true
