resources:
    App\Entity\Module:
        -   uriTemplate: /courses/{courseUuid}/modules
            uriVariables:
                courseUuid:
                    fromClass: App\Entity\Course
                    toProperty: course
                    identifiers: [ uuid ]
            normalizationContext:
                groups: [ 'module:list' ]
            denormalizationContext:
                groups: [ 'module:write' ]
            operations:
                ApiPlatform\Metadata\GetCollection:
                    cacheHeaders:
                        shared_max_age: 1800
                        max_age: 60
                ApiPlatform\Metadata\Post: ~

        -   uriTemplate: /courses/{courseUuid}/modules/{id}
            uriVariables:
                courseUuid:
                    fromClass: App\Entity\Course
                    toProperty: course
                    identifiers: [ uuid ]
                id:
                    fromClass: App\Entity\Module
                    identifiers: [ id ]
            normalizationContext:
                groups: [ 'module:read' ]
            operations:
                ApiPlatform\Metadata\Get:
                    cacheHeaders:
                        shared_max_age: 1800
                        max_age: 60
                ApiPlatform\Metadata\Patch: ~
                ApiPlatform\Metadata\Delete: ~
