resources:
    App\Entity\Student:
         normalizationContext:
             groups: ['student:read']
         denormalizationContext:
             groups: ['student:write']
         operations:
             ApiPlatform\Metadata\GetCollection:
                 cacheHeaders:
                     max_age: 0
             ApiPlatform\Metadata\Get:
                 cacheHeaders:
                     max_age: 60
             ApiPlatform\Metadata\Post: ~
             ApiPlatform\Metadata\Patch: ~
             ApiPlatform\Metadata\Delete: ~
properties:
    App\Entity\Student:
        id:
            identifier: false
        uuid:
            identifier: true
